[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29.10"
softbuffer = "0.4.1"
log = "0.4"

html = { path = "../html" }
css = { path = "../css" }
layout = { path = "../layout" }
paint = { path = "../paint" }